# Generated by Django 5.1.4 on 2024-12-15 20:32

import animals_app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='average_age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=255, validators=[animals_app.validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='animals',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
